In [1]:
import numpy as np

In [102]:
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[-2.    1.  ]
 [ 1.75 -0.75]]


In [103]:
ones_array = np.ones((4, 2))
print("All Ones Array:\n", ones_array)

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [104]:
filled_array = np.full((3, 3), 7)
print("Filled Array:\n", filled_array)

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [105]:
array_for_zeros_like = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(array_for_zeros_like)
print("Zeros Like Array:\n", zeros_like_array)

Zeros Like Array:
 [[0 0]
 [0 0]]


In [106]:
ones_like_array = np.ones_like(array_for_zeros_like)
print("Ones Like Array:\n", ones_like_array)

Ones Like Array:
 [[1 1]
 [1 1]]


In [107]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy Array:\n", numpy_array)

Numpy Array:
 [1 2 3 4]


In [108]:
arr1 = np.arange(10, 50)
print("Array from 10 to 49:\n", arr1)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [109]:
arr2 = np.arange(9).reshape(3, 3)
print("3x3 Matrix:\n", arr2)


3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [110]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [111]:
random_array = np.random.random(30)
mean_random_array = random_array.mean()
print("Mean of Random Array:", mean_random_array)

Mean of Random Array: 0.4013791246486956


In [113]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Min Value:", min_value, "\nMax Value:", max_value)

Min Value: 0.000563732058073918 
Max Value: 0.9859782329313361


In [114]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero Array with 5th Element as 1:\n", zero_array)

Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
zero_array

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [115]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


In [21]:
special = np.ones((5,5))
special

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
special[1:-1,1:-1]=0

In [116]:
print("2D Array with Border 1 and Inside 0:\n", special)


2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [118]:
checkboard = np.zeros((8,8),dtype="int")
checkboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [119]:
checkboard[1::2, ::2] = 1
checkboard[::2, 1::2] = 1

In [121]:
print("Checkerboard Pattern:\n", checkboard)


Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## **Array Operations**

In [122]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [123]:
add_result = np.add(x, y)
print("Addition of x and y:\n", add_result)

Addition of x and y:
 [[ 6  8]
 [10 13]]


In [124]:
subtract_result = np.subtract(x, y)
print("Subtraction of x and y:\n", subtract_result)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [125]:
multiply_result = x * 3
print("Multiply x by 3:\n", multiply_result)

Multiply x by 3:
 [[ 3  6]
 [ 9 15]]


In [126]:
square_result = np.square(x)
print("Square of x:\n", square_result)

Square of x:
 [[ 1  4]
 [ 9 25]]


In [127]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)


Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [129]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [38]:
np.hstack((v,w))

array([ 9, 10, 11, 12])

In [131]:
try:
    concatenate_xv = np.concatenate((x, v), axis=1)
except Exception as e:
    print("Error while concatenating x and v:", e)

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


The error occurs because the shapes of x and v are incompatible for concatenation.

x is a 2-dimensional array with shape (2, 2).
v is a 1-dimensional array with shape (2,).
When trying to concatenate arrays, NumPy expects the arrays to have matching dimensions. In this case, x has 2 dimensions, while v has only 1 dimension, leading to a ValueError.

## **Matrix Operations**

In [40]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

**To Prove `A.A−1 = I.`**

In [44]:
A_inv = np.linalg.inv(A)

In [45]:
I = np.dot(A, A_inv)
I

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [47]:
print("Matrix A:\n", A)

Matrix A:
 [[3 4]
 [7 8]]


In [48]:
print("Inverse of A (A_inv):\n", A_inv)

Inverse of A (A_inv):
 [[-2.    1.  ]
 [ 1.75 -0.75]]


In [49]:
print("Product of A and A_inv (A . A_inv):\n", I)

Product of A and A_inv (A . A_inv):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [50]:
print("Is A . A_inv close to the identity matrix? ", np.allclose(I, np.eye(2)))

Is A . A_inv close to the identity matrix?  True


Hence, Matrix A when multiplied with its inverse is very close to the Identity matrix of 2d. Therefore, they are equal.

**To Prove `AB ̸= BA`**

In [57]:
print("Product AB:\n", A@B)

Product AB:
 [[23 13]
 [51 29]]


In [56]:
print("Product BA:\n", B@A)

Product BA:
 [[36 44]
 [13 16]]


In [60]:
print("Is AB equal to BA?", np.array_equal(A@B, B@A))

Is AB equal to BA? False


Therefore, AB is not equal to BA.

**To Prove `(AB)T = BTAT`**

In [61]:
AB_T = (A @ B).T
BT_AT = B.T @ A.T

In [62]:
print("Matrix A:\n", A)

Matrix A:
 [[3 4]
 [7 8]]


In [63]:
print("Matrix B:\n", B)

Matrix B:
 [[5 3]
 [2 1]]


In [64]:
print("Transpose of AB:\n", AB_T)

Transpose of AB:
 [[23 51]
 [13 29]]


In [65]:
print("Product of B^T and A^T:\n", BT_AT)

Product of B^T and A^T:
 [[23 51]
 [13 29]]


In [67]:
print("Is AB Transpose equal to B Transpose A Transpose?", np.array_equal(AB_T, BT_AT))

Is AB Transpose equal to B Transpose A Transpose? True


Hence, AB Transpose is equal to B Transpose A Transpose.

- 2x − 3y + z = −1
- x − y + 2z = −3
- 3x + y − z = 9

In [69]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

In [70]:
A_inv = np.linalg.inv(A)

In [72]:
X = np.dot(A_inv, B)

In [75]:
print(f"Solution: x = {X[0]}, y = {X[1]}, z = {X[2]}")

Solution: x = 2.0, y = 1.0, z = -2.0


### Final Solution:
- \( x = 2.0 \)
- \( y = 1.0 \)
- \( z = -2.0 \)


In [79]:
import time
import random

**1. Element-wise Addition:**

In [95]:
py_list1 = [random.random() for _ in range(1000000)]
py_list2 = [random.random() for _ in range(1000000)]

np_array1 = np.random.rand(1000000)
np_array2 = np.random.rand(1000000)

tic_list = time.time()
result_py_list = [py_list1[i] + py_list2[i] for i in range(len(py_list1))]
toc_list = time.time()
print("Python list time: ", toc_list - tic_list)

tic_array = time.time()
result_np_array = np_array1 + np_array2
toc_array = time.time()
print("NumPy array time: ", toc_array - tic_array)

print(f"NumPy array is {int((toc_list - tic_list) / (toc_array - tic_array))} times faster")

Python list time:  0.0398259162902832
NumPy array time:  0.001291036605834961
NumPy array is 30 times faster


**2. Element-wise Multiplication**

In [96]:
py_list1 = [random.random() for _ in range(1000000)]
py_list2 = [random.random() for _ in range(1000000)]

np_array1 = np.random.rand(1000000)
np_array2 = np.random.rand(1000000)

tic_list = time.time()
result_py_list = [py_list1[i] * py_list2[i] for i in range(len(py_list1))]
toc_list = time.time()
print("Python list time: ", toc_list - tic_list)

tic_array = time.time()
result_np_array = np_array1 @ np_array2
toc_array = time.time()
print("NumPy array time: ", toc_array - tic_array)

print(f"NumPy array is {int((toc_list - tic_list) / (toc_array - tic_array))} times faster")

Python list time:  0.03865337371826172
NumPy array time:  0.0008745193481445312
NumPy array is 44 times faster


**3. Dot Product**

In [100]:
py_list1 = [random.random() for _ in range(1000000)]
py_list2 = [random.random() for _ in range(1000000)]
np_array1 = np.random.rand(1000000)
np_array2 = np.random.rand(1000000)

tic_list = time.time()
dot_product_py_list = sum(py_list1[i] * py_list2[i] for i in range(len(py_list1)))
toc_list = time.time()
print("Python list time: ", toc_list - tic_list)

tic_array = time.time()
dot_product_np_array = np.dot(np_array1, np_array2)
toc_array = time.time()
print("NumPy array time: ", toc_array - tic_array)

print(f"NumPy array is {int((toc_list - tic_list) / (toc_array - tic_array))} times faster.")

Python list time:  0.034938812255859375
NumPy array time:  0.0006897449493408203
NumPy array is 50 times faster.


In [101]:
matrix1 = [[random.random() for _ in range(1000)] for _ in range(1000)]
matrix2 = [[random.random() for _ in range(1000)] for _ in range(1000)]
np_matrix1 = np.random.rand(1000, 1000)
np_matrix2 = np.random.rand(1000, 1000)

tic_list_matrix = time.time()
result_py_matrix = []
for i in range(1000):
    row = []
    for j in range(1000):
        element = 0
        for k in range(1000):
            element += matrix1[i][k] * matrix2[k][j]
        row.append(element)
    result_py_matrix.append(row)
toc_list_matrix = time.time()
print("Python list matrix multiplication time: ", toc_list_matrix - tic_list_matrix)

tic_array_matrix = time.time()
result_np_matrix = np.dot(np_matrix1, np_matrix2)
toc_array_matrix = time.time()
print("NumPy array matrix multiplication time: ", toc_array_matrix - tic_array_matrix)

print(f"NumPy array is {int((toc_list_matrix - tic_list_matrix) / (toc_array_matrix - tic_array_matrix))} times faster for matrix multiplication")

Python list matrix multiplication time:  90.82327628135681
NumPy array matrix multiplication time:  0.011690378189086914
NumPy array is 7769 times faster for matrix multiplication
