In [1]:
#sidant shrestha
#2408637
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/DataSets/student.csv")

#print top5 of the dataset
print("Top 5 data of dataset: ")
print(df.head())

#print bottom5 of dataset
print("\nBottom 5 data of dataset: ")
print(df.tail())

#print information of dataset
print("\nInformation of dataset:")
print(df.info)

#print descriptive info about the dataset
print("\nDescriptive info about the dataset:")
print(df.describe)

Top 5 data of dataset: 
   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

Bottom 5 data of dataset: 
     Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

Information of dataset:
<bound method DataFrame.info of      Math  Reading  Writing
0      48       68       63
1      62       81       72
2      79       80       78
3      76       83       79
4      59       64       62
..    ...      ...      ...
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

[1000 rows x 3 columns]>

Descriptive info about the dataset:
<bound method NDFrame.describe of      Math  Reading  Writing
0      48       68       63
1      62       81       72
2      79       80       78
3      76       83    

In [2]:
# Define the label column name
label_column = 'Writing'

# Separate features (X) and label (Y)
X = df.drop(columns=[label_column])  # Drop the label column to get features
Y = df[label_column]  # Extract the label column

print("\nFeatures (X):")
print(X.head())
print("\nLabel (Y):")
print(Y.head())


Features (X):
   Math  Reading
0    48       68
1    62       81
2    79       80
3    76       83
4    59       64

Label (Y):
0    63
1    72
2    78
3    79
4    62
Name: Writing, dtype: int64


In [3]:
import numpy as np

# Define the dimensions
d = 3  # Number of features
n = 5  # Number of samples/examples

# Create W (weight vector) of shape (d, 1)
W = np.random.rand(d, 1)

# Create X (feature matrix) of shape (d, n)
X = np.random.rand(d, n)

# Compute Y = W^T X
Y = np.dot(W.T, X)

# Display matrices
print("Matrix W (weights):")
print(W)

print("\nMatrix X (features):")
print(X)

print("\nMatrix Y (output):")
print(Y)


Matrix W (weights):
[[0.13370801]
 [0.4592906 ]
 [0.82995029]]

Matrix X (features):
[[0.48129828 0.25497554 0.25203021 0.47496192 0.15215194]
 [0.39076744 0.98393524 0.51862867 0.31062321 0.61325906]
 [0.87773453 0.33614798 0.66376253 0.78930559 0.74059902]]

Matrix Y (output):
[[0.97230528 0.76499059 0.82278964 0.86125694 0.91666842]]


In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

# Example dataset
X = np.random.rand(100, 10)  # 100 samples, 10 features
Y = np.random.randint(0, 2, size=(100,))  # 100 binary labels

print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

# Split the dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Display the shapes of the splits
print("Training set:")
print(f"Features (X_train): {X_train.shape}, Labels (Y_train): {Y_train.shape}")

print("\nTest set:")
print(f"Features (X_test): {X_test.shape}, Labels (Y_test): {Y_test.shape}")


Shape of X: (100, 10)
Shape of Y: (100,)
Training set:
Features (X_train): (80, 10), Labels (Y_train): (80,)

Test set:
Features (X_test): (20, 10), Labels (Y_test): (20,)


In [7]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/DataSets/student.csv")

# Define the label column name
label_column = 'Writing'

# Separate features (X) and label (Y)
X = df.drop(columns=[label_column])
Y = df[label_column]

print("\nFeatures (X):")
print(X.head())

print("\nLabel (Y):")
print(Y.head())




Features (X):
   Math  Reading
0    48       68
1    62       81
2    79       80
3    76       83
4    59       64

Label (Y):
0    63
1    72
2    78
3    79
4    62
Name: Writing, dtype: int64


In [8]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and test sets using an 80-20 split
test_size = 0.2

# Perform the split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=test_size, random_state=42)

# Display the shapes of the splits
print(f"Training set shape (X_train, Y_train): {X_train.shape}, {Y_train.shape}")
print(f"Test set shape (X_test, Y_test): {X_test.shape}, {Y_test.shape}")


Training set shape (X_train, Y_train): (800, 2), (800,)
Test set shape (X_test, Y_test): (200, 2), (200,)


In [9]:
# Gradient Descent Function
def gradient_descent(X, Y, learning_rate=0.01, iterations=1000):
    m = len(Y)  # Number of samples
    d = X.shape[1]  # Number of features
    W = np.zeros(d)  # Initialize weight vector

    # Gradient Descent Loop
    for _ in range(iterations):
        # Compute predictions
        predictions = np.dot(X, W)

        # Calculate gradient
        gradient = - (2/m) * np.dot(X.T, (Y - predictions))

        # Update weights
        W -= learning_rate * gradient

    return W

# Train the model using gradient descent on the training set
W = gradient_descent(X_train.values, Y_train.values, learning_rate=0.01, iterations=1000)

# Display learned weights
print(f"Learned weights: {W}")


Learned weights: [nan nan]


<ipython-input-9-667e34756a9f>:16: RuntimeWarning: invalid value encountered in subtract
  W -= learning_rate * gradient


In [10]:
from sklearn.metrics import mean_squared_error, r2_score

# Predict using the trained model
Y_pred = np.dot(X_test, W)

# If Y_pred contains NaN, replace NaNs with 0 (or any other appropriate value)
Y_pred = np.nan_to_num(Y_pred, nan=0.0)

# Calculate RMSE (Root Mean Squared Error)
rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))

# Calculate R² (R-squared)
r2 = r2_score(Y_test, Y_pred)

# Display the evaluation metrics
print(f"RMSE: {rmse}")
print(f"R²: {r2}")


RMSE: 70.19622496972326
R²: -18.685008543136547


In [11]:
# Experiment with different learning rates
learning_rates = [0.001, 0.01, 0.1, 1, 10]
results = {}

for lr in learning_rates:
    # Train the model using gradient descent on the training set
    W = gradient_descent(X_train.values, Y_train.values, learning_rate=lr, iterations=1000)

    # Predict using the trained model
    Y_pred = np.dot(X_test, W)

    # If Y_pred contains NaN, replace NaNs with 0 (or any other appropriate value)
    Y_pred = np.nan_to_num(Y_pred, nan=0.0)

    # Calculate RMSE (Root Mean Squared Error)
    rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))

    # Calculate R² (R-squared)
    r2 = r2_score(Y_test, Y_pred)

    # Store the results
    results[lr] = {'RMSE': rmse, 'R²': r2}

# Display the results for each learning rate
for lr, result in results.items():
    print(f"Learning Rate: {lr}")
    print(f"RMSE: {result['RMSE']}")
    print(f"R²: {result['R²']}")
    print('-' * 40)


Learning Rate: 0.001
RMSE: 70.19622496972326
R²: -18.685008543136547
----------------------------------------
Learning Rate: 0.01
RMSE: 70.19622496972326
R²: -18.685008543136547
----------------------------------------
Learning Rate: 0.1
RMSE: 70.19622496972326
R²: -18.685008543136547
----------------------------------------
Learning Rate: 1
RMSE: 70.19622496972326
R²: -18.685008543136547
----------------------------------------
Learning Rate: 10
RMSE: 70.19622496972326
R²: -18.685008543136547
----------------------------------------


<ipython-input-9-667e34756a9f>:16: RuntimeWarning: invalid value encountered in subtract
  W -= learning_rate * gradient
<ipython-input-9-667e34756a9f>:16: RuntimeWarning: invalid value encountered in subtract
  W -= learning_rate * gradient
<ipython-input-9-667e34756a9f>:16: RuntimeWarning: invalid value encountered in subtract
  W -= learning_rate * gradient
<ipython-input-9-667e34756a9f>:16: RuntimeWarning: invalid value encountered in subtract
  W -= learning_rate * gradient
<ipython-input-9-667e34756a9f>:16: RuntimeWarning: invalid value encountered in subtract
  W -= learning_rate * gradient
